"""create_all_tables

Revision ID: 73b51b0ba65e
Revises: 914189a814f9
Create Date: 2025-12-05 18:29:50.528473

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73b51b0ba65e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disciplinas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("carga_horaria", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_disciplinas_codigo"), "disciplinas", ["codigo"], unique=True
    )
    op.create_index(op.f("ix_disciplinas_id"), "disciplinas", ["id"], unique=False)
    op.create_index(op.f("ix_disciplinas_nome"), "disciplinas", ["nome"], unique=False)

    # Create escolas table
    op.create_table(
        "escolas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("endereco", sa.String(), nullable=True),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_escolas_id"), "escolas", ["id"], unique=False)
    op.create_index(op.f("ix_escolas_nome"), "escolas", ["nome"], unique=False)

    op.create_table(
        "turmas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("ano_letivo", sa.Integer(), nullable=False),
        sa.Column("serie", sa.String(), nullable=False),
        sa.Column(
            "turno",
            sa.Enum("MATUTINO", "VESPERTINO", "NOTURNO", name="turno"),
            nullable=False,
        ),
        sa.Column("capacidade", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turmas_codigo"), "turmas", ["codigo"], unique=True)
    op.create_index(op.f("ix_turmas_id"), "turmas", ["id"], unique=False)
    op.create_index(op.f("ix_turmas_nome"), "turmas", ["nome"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("senha_hash", sa.String(), nullable=False),
        sa.Column("nome_completo", sa.String(), nullable=False),
        sa.Column("telefone", sa.String(), nullable=True),
        sa.Column(
            "tipo_usuario",
            sa.Enum("PROFESSOR", "RESPONSAVEL", "ALUNO", "GESTOR", name="tipousuario"),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "eventos_escolares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("turma_id", sa.Integer(), nullable=True),
        sa.Column("criado_por_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "REUNIAO",
                "FESTA",
                "APRESENTACAO",
                "PALESTRA",
                "EXCURSAO",
                "OUTRO",
                name="tipoevento",
            ),
            nullable=True,
        ),
        sa.Column("data_evento", sa.Date(), nullable=False),
        sa.Column("hora_inicio", sa.Time(), nullable=True),
        sa.Column("hora_fim", sa.Time(), nullable=True),
        sa.Column("local", sa.String(), nullable=True),
        sa.Column("publico_alvo", sa.String(), nullable=True),
        sa.Column("requer_confirmacao", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["criado_por_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["turma_id"], ["turmas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eventos_escolares_data_evento"),
        "eventos_escolares",
        ["data_evento"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eventos_escolares_id"), "eventos_escolares", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_eventos_escolares_titulo"),
        "eventos_escolares",
        ["titulo"],
        unique=False,
    )
    op.create_table(
        "gestores_escolares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.String(), nullable=True),
        sa.Column("cargo", sa.String(), nullable=True),
        sa.Column("departamento", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_gestores_escolares_id"), "gestores_escolares", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_gestores_escolares_matricula"),
        "gestores_escolares",
        ["matricula"],
        unique=True,
    )
    op.create_table(
        "mensagens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remetente_id", sa.Integer(), nullable=False),
        sa.Column("destinatario_id", sa.Integer(), nullable=False),
        sa.Column("assunto", sa.String(), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column(
            "tipo_midia",
            sa.Enum("TEXTO", "AUDIO", "VIDEO", "IMAGEM", name="tipomidia"),
            nullable=True,
        ),
        sa.Column("midia_url", sa.String(), nullable=True),
        sa.Column(
            "enviada_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("lida_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmacao_leitura", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["destinatario_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remetente_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mensagens_destinatario_id"),
        "mensagens",
        ["destinatario_id"],
        unique=False,
    )
    op.create_index(op.f("ix_mensagens_id"), "mensagens", ["id"], unique=False)
    op.create_index(
        op.f("ix_mensagens_remetente_id"), "mensagens", ["remetente_id"], unique=False
    )
    op.create_table(
        "metricas_engajamento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("acao", sa.String(), nullable=False),
        sa.Column("categoria", sa.String(), nullable=True),
        sa.Column("referencia_id", sa.Integer(), nullable=True),
        sa.Column("referencia_tipo", sa.String(), nullable=True),
        sa.Column("tempo_sessao", sa.Float(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("dispositivo", sa.String(), nullable=True),
        sa.Column("navegador", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metricas_engajamento_acao"),
        "metricas_engajamento",
        ["acao"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metricas_engajamento_categoria"),
        "metricas_engajamento",
        ["categoria"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metricas_engajamento_id"), "metricas_engajamento", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_metricas_engajamento_timestamp"),
        "metricas_engajamento",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metricas_engajamento_usuario_id"),
        "metricas_engajamento",
        ["usuario_id"],
        unique=False,
    )
    op.create_table(
        "notificacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("mensagem", sa.Text(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "AVISO", "LEMBRETE", "ALERTA", "INFORMACAO", name="tiponotificacao"
            ),
            nullable=True,
        ),
        sa.Column("link_referencia", sa.String(), nullable=True),
        sa.Column("lida", sa.Boolean(), nullable=True),
        sa.Column(
            "criada_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("lida_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notificacoes_id"), "notificacoes", ["id"], unique=False)
    op.create_index(
        op.f("ix_notificacoes_usuario_id"), "notificacoes", ["usuario_id"], unique=False
    )
    op.create_table(
        "professores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.String(), nullable=True),
        sa.Column("formacao", sa.String(), nullable=True),
        sa.Column("especializacao", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_professores_id"), "professores", ["id"], unique=False)
    op.create_index(
        op.f("ix_professores_matricula"), "professores", ["matricula"], unique=True
    )
    op.create_table(
        "responsaveis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("parentesco", sa.String(), nullable=True),
        sa.Column(
            "literacia_digital",
            sa.Enum("BAIXO", "MEDIO", "ALTO", name="nivelliteraciadigital"),
            nullable=True,
        ),
        sa.Column("preferencia_audio", sa.Boolean(), nullable=True),
        sa.Column("preferencia_video", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_responsaveis_cpf"), "responsaveis", ["cpf"], unique=True)
    op.create_index(op.f("ix_responsaveis_id"), "responsaveis", ["id"], unique=False)
    op.create_table(
        "alunos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("responsavel_id", sa.Integer(), nullable=True),
        sa.Column("turma_id", sa.Integer(), nullable=True),
        sa.Column("matricula", sa.String(), nullable=False),
        sa.Column("data_nascimento", sa.Date(), nullable=True),
        sa.Column("necessidades_especiais", sa.Boolean(), nullable=True),
        sa.Column("descricao_necessidades", sa.Text(), nullable=True),
        sa.Column("pei_ativo", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["responsavel_id"], ["responsaveis.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["turma_id"], ["turmas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_alunos_id"), "alunos", ["id"], unique=False)
    op.create_index(op.f("ix_alunos_matricula"), "alunos", ["matricula"], unique=True)
    op.create_table(
        "atividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("turma_id", sa.Integer(), nullable=False),
        sa.Column("disciplina_id", sa.Integer(), nullable=False),
        sa.Column("professor_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column(
            "data_criacao",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("data_entrega", sa.Date(), nullable=False),
        sa.Column("pontuacao_maxima", sa.Integer(), nullable=True),
        sa.Column("anexo_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["disciplina_id"], ["disciplinas.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["professor_id"], ["professores.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["turma_id"], ["turmas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_atividades_id"), "atividades", ["id"], unique=False)
    op.create_index(
        op.f("ix_atividades_titulo"), "atividades", ["titulo"], unique=False
    )
    op.create_table(
        "professor_disciplina",
        sa.Column("professor_id", sa.Integer(), nullable=True),
        sa.Column("disciplina_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["disciplina_id"], ["disciplinas.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["professor_id"], ["professores.id"], ondelete="CASCADE"
        ),
    )
    op.create_table(
        "professor_turma",
        sa.Column("professor_id", sa.Integer(), nullable=True),
        sa.Column("turma_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professor_id"], ["professores.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["turma_id"], ["turmas.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "avaliacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.Integer(), nullable=False),
        sa.Column("disciplina_id", sa.Integer(), nullable=False),
        sa.Column("professor_id", sa.Integer(), nullable=True),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("nota", sa.Float(), nullable=True),
        sa.Column("peso", sa.Float(), nullable=True),
        sa.Column("data_avaliacao", sa.Date(), nullable=False),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["disciplina_id"], ["disciplinas.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["professor_id"], ["professores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_avaliacoes_id"), "avaliacoes", ["id"], unique=False)
    op.create_table(
        "entregas_atividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("atividade_id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_entrega",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("anexo_url", sa.String(), nullable=True),
        sa.Column("nota", sa.Integer(), nullable=True),
        sa.Column("concluida", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["atividade_id"], ["atividades.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entregas_atividades_id"), "entregas_atividades", ["id"], unique=False
    )
    op.create_table(
        "peis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aluno_id", sa.Integer(), nullable=False),
        sa.Column("elaborado_por_id", sa.Integer(), nullable=True),
        sa.Column("data_inicio", sa.Date(), nullable=False),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column("objetivos", sa.Text(), nullable=False),
        sa.Column("adaptacoes_curriculares", sa.Text(), nullable=True),
        sa.Column("estrategias_ensino", sa.Text(), nullable=True),
        sa.Column("recursos_necessarios", sa.Text(), nullable=True),
        sa.Column("criterios_avaliacao", sa.Text(), nullable=True),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Integer(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["elaborado_por_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_peis_aluno_id"), "peis", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_peis_id"), "peis", ["id"], unique=False)
    op.create_table(
        "intervencoes_pedagogicas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pei_id", sa.Integer(), nullable=False),
        sa.Column("professor_id", sa.Integer(), nullable=True),
        sa.Column("data_intervencao", sa.Date(), nullable=False),
        sa.Column("tipo_intervencao", sa.String(), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("resultados_observados", sa.Text(), nullable=True),
        sa.Column("proximos_passos", sa.Text(), nullable=True),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["pei_id"], ["peis.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["professor_id"], ["professores.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intervencoes_pedagogicas_id"),
        "intervencoes_pedagogicas",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intervencoes_pedagogicas_pei_id"),
        "intervencoes_pedagogicas",
        ["pei_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intervencoes_pedagogicas_pei_id"),
        table_name="intervencoes_pedagogicas",
    )
    op.drop_index(
        op.f("ix_intervencoes_pedagogicas_id"), table_name="intervencoes_pedagogicas"
    )
    op.drop_table("intervencoes_pedagogicas")
    op.drop_index(op.f("ix_peis_id"), table_name="peis")
    op.drop_index(op.f("ix_peis_aluno_id"), table_name="peis")
    op.drop_table("peis")
    op.drop_index(op.f("ix_entregas_atividades_id"), table_name="entregas_atividades")
    op.drop_table("entregas_atividades")
    op.drop_index(op.f("ix_avaliacoes_id"), table_name="avaliacoes")
    op.drop_table("avaliacoes")
    op.drop_table("professor_turma")
    op.drop_table("professor_disciplina")
    op.drop_index(op.f("ix_atividades_titulo"), table_name="atividades")
    op.drop_index(op.f("ix_atividades_id"), table_name="atividades")
    op.drop_table("atividades")
    op.drop_index(op.f("ix_alunos_matricula"), table_name="alunos")
    op.drop_index(op.f("ix_alunos_id"), table_name="alunos")
    op.drop_table("alunos")
    op.drop_index(op.f("ix_responsaveis_id"), table_name="responsaveis")
    op.drop_index(op.f("ix_responsaveis_cpf"), table_name="responsaveis")
    op.drop_table("responsaveis")
    op.drop_index(op.f("ix_professores_matricula"), table_name="professores")
    op.drop_index(op.f("ix_professores_id"), table_name="professores")
    op.drop_table("professores")
    op.drop_index(op.f("ix_notificacoes_usuario_id"), table_name="notificacoes")
    op.drop_index(op.f("ix_notificacoes_id"), table_name="notificacoes")
    op.drop_table("notificacoes")
    op.drop_index(
        op.f("ix_metricas_engajamento_usuario_id"), table_name="metricas_engajamento"
    )
    op.drop_index(
        op.f("ix_metricas_engajamento_timestamp"), table_name="metricas_engajamento"
    )
    op.drop_index(op.f("ix_metricas_engajamento_id"), table_name="metricas_engajamento")
    op.drop_index(
        op.f("ix_metricas_engajamento_categoria"), table_name="metricas_engajamento"
    )
    op.drop_index(
        op.f("ix_metricas_engajamento_acao"), table_name="metricas_engajamento"
    )
    op.drop_table("metricas_engajamento")
    op.drop_index(op.f("ix_mensagens_remetente_id"), table_name="mensagens")
    op.drop_index(op.f("ix_mensagens_id"), table_name="mensagens")
    op.drop_index(op.f("ix_mensagens_destinatario_id"), table_name="mensagens")
    op.drop_table("mensagens")
    op.drop_index(
        op.f("ix_gestores_escolares_matricula"), table_name="gestores_escolares"
    )
    op.drop_index(op.f("ix_gestores_escolares_id"), table_name="gestores_escolares")
    op.drop_table("gestores_escolares")
    op.drop_index(op.f("ix_gestores_escolares_id"), table_name="gestores_escolares")
    op.drop_table("gestores_escolares")
    op.drop_index(op.f("ix_eventos_escolares_turma_id"), table_name="eventos_escolares")
    op.drop_index(op.f("ix_eventos_escolares_id"), table_name="eventos_escolares")
    op.drop_table("eventos_escolares")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_turmas_nome"), table_name="turmas")
    op.drop_index(op.f("ix_turmas_id"), table_name="turmas")
    op.drop_index(op.f("ix_turmas_codigo"), table_name="turmas")
    op.drop_table("turmas")
    op.drop_index(op.f("ix_escolas_nome"), table_name="escolas")
    op.drop_index(op.f("ix_escolas_id"), table_name="escolas")
    op.drop_table("escolas")
    op.drop_index(op.f("ix_disciplinas_nome"), table_name="disciplinas")
    op.drop_index(op.f("ix_disciplinas_id"), table_name="disciplinas")
    op.drop_index(op.f("ix_disciplinas_codigo"), table_name="disciplinas")
    op.drop_table("disciplinas")
    # ### end Alembic commands ###
